Component/scatter plot/add labels
plot-a-pi/pi pull request #35
Opened 2020-02-25 19:23 UTC by alanhermanns

2020-02-25 21:00 UTC, JMoneymaker commented on src/components/graphs/Scatterplot.js
> +    const removeLabelText = (localThis, args) => {
localThis isn't super clear to me...

2020-02-25 21:01 UTC, JMoneymaker commented on src/components/graphs/Scatterplot.js
> +    // const zoomBehavior = zoom()
I think we can just delete all the zoomBehavior stuff.

2020-02-25 21:02 UTC, JMoneymaker requested changes
Could you change the This thing? Sorry, it's really confusing to me.

2020-02-25 21:11 UTC, licarpen requested changes
what is localThis?

2020-02-26 00:33 UTC, licarpen approved these changes

2020-02-26 00:34 UTC, yaycub approved these changes

2020-02-26 00:52 UTC, JMoneymaker approved these changes

2020-02-26 00:54 UTC, merged