Svg/labels
plot-a-pi/pi pull request #50
Opened 2020-02-26 22:25 UTC by alanhermanns

2020-02-26 22:56 UTC, avnit77 approved these changes

2020-02-26 23:03 UTC, licarpen requested changes
Xmax and Ymax should not be passed in as props for montecarlo

2020-02-27 00:07 UTC, licarpen approved these changes

2020-02-27 00:07 UTC, avnit77 approved these changes

2020-02-27 00:08 UTC, merged